a = int(input("Enter value of A: "))
b = int(input("Enter value of B: "))
c = int(input("Enter value of C: "))
d = int(input("Enter value of D: "))
e = int(input("Enter value of E: "))
f = int(input("Enter value of F: "))
g = int(input("Enter value of G: "))
result = (a+b-c)*d/(e+f+g)
print("Result is : ", result)