import turtle
turtle.pencolor('yellow')
turtle.pensize(5)
turtle.forward(50)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(100)
turtle.back(50)
turtle.right(90)
turtle.forward(50)
turtle.done()